#!/usr/bin/env python3
"""Compute the predeclared agreement statistics for the blinded visual review.

Implements docs/HUMAN_EVALUATION.md section 4 exactly and in the order it lists:
raw agreement, three-class Cohen's kappa, conservatively collapsed binary kappa,
and PABAK wherever the kappa paradox appears. Nothing here chooses a statistic
after seeing the data, and nothing is imputed: unrated cells are counted and
reported as unrated.

Usage:
    python scripts/analyze_human_review.py \
        reports/v3/manual_review/human_review__rater-a.csv \
        reports/v3/manual_review/human_review__rater-b.csv
"""

from __future__ import annotations

import argparse
import csv
import math
import sys
from collections import Counter
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT_DIR = REPO / "reports" / "v3" / "manual_review"

VALUES = ("yes", "no", "uncertain")

# Conservative collapse from docs/HUMAN_EVALUATION.md section 3.
# pass_on is the single response that counts as a pass; everything else,
# including `uncertain`, fails. `descriptive` fields are reported but gate nothing.
FIELDS = {
    "original_label_still_valid": {"pass_on": "yes", "descriptive": False},
    "image_usable": {"pass_on": "yes", "descriptive": False},
    "text_readable": {"pass_on": "yes", "descriptive": False},
    "text_too_obvious": {"pass_on": "yes", "descriptive": True},
    "text_completely_invisible": {"pass_on": "no", "descriptive": False},
    "critical_damage_obscured": {"pass_on": "no", "descriptive": False},
    "layout_plausible": {"pass_on": "yes", "descriptive": False},
    "approve": {"pass_on": "yes", "descriptive": False},
}

# Rater-quality floor, predeclared. Not a stealth floor.
FLOOR_FIELDS = ("text_readable", "critical_damage_obscured")
FLOOR_RAW = 0.80
FLOOR_KAPPA = 0.40


def wilson(k: int, n: int, z: float = 1.959963985) -> tuple[float, float]:
    if n == 0:
        return (0.0, 0.0)
    p = k / n
    d = 1 + z * z / n
    c = (p + z * z / (2 * n)) / d
    h = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / d
    return (max(0.0, c - h) * 100, min(1.0, c + h) * 100)


def cohen_kappa(pairs: list[tuple[str, str]]) -> float | None:
    """Unweighted Cohen's kappa over whatever label set actually appears."""
    n = len(pairs)
    if n == 0:
        return None
    labels = sorted({v for pair in pairs for v in pair})
    po = sum(1 for a, b in pairs if a == b) / n
    ca, cb = Counter(a for a, _ in pairs), Counter(b for _, b in pairs)
    pe = sum((ca[l] / n) * (cb[l] / n) for l in labels)
    if abs(1 - pe) < 1e-12:
        return None  # undefined: one label saturates both raters
    return (po - pe) / (1 - pe)


def pabak(po: float) -> float:
    return 2 * po - 1


def read(path: Path) -> tuple[str, dict[tuple[str, str], dict[str, str]]]:
    rows = list(csv.DictReader(path.open()))
    if not rows:
        sys.exit(f"{path}: empty file")
    ids = {r.get("reviewer_id", "").strip() for r in rows}
    ids.discard("")
    if len(ids) != 1:
        sys.exit(f"{path}: expected exactly one reviewer_id, found {sorted(ids) or 'none'}")
    table = {}
    for r in rows:
        table[(r["sample_id"], r["condition"])] = r
    if len(table) != len(rows):
        sys.exit(f"{path}: duplicate sample/condition rows")
    return ids.pop(), table


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("files", nargs="+", type=Path, help="one exported CSV per reviewer")
    ap.add_argument("--out", type=Path, default=OUT_DIR / "AGREEMENT.md")
    args = ap.parse_args()

    if len(args.files) < 2:
        sys.exit("need at least two independent reviewer files")
    if len(args.files) > 2:
        sys.exit("this script implements two-rater Cohen's kappa; for 3+ raters the "
                 "protocol requires Krippendorff's alpha instead")

    (id_a, a), (id_b, b) = (read(p) for p in args.files)
    if id_a == id_b:
        sys.exit(f"both files carry reviewer_id '{id_a}'; the passes must be independent")

    keys = sorted(set(a) & set(b))
    only_a, only_b = set(a) - set(b), set(b) - set(a)
    if only_a or only_b:
        sys.exit(f"the two files do not cover the same items: "
                 f"{len(only_a)} only in {id_a}, {len(only_b)} only in {id_b}")

    L: list[str] = []
    w = L.append
    w("# Human visual review — agreement report")
    w("")
    w(f"Reviewers: `{id_a}` and `{id_b}`. Items compared: **{len(keys)}**.")
    w("")
    w("Generated by `scripts/analyze_human_review.py` from the two independent exports. "
      "Statistics and the collapse rules follow `docs/HUMAN_EVALUATION.md` section 3--4 "
      "and were fixed before any rating was collected.")
    w("")

    # --- completeness -------------------------------------------------------
    unrated = {rid: 0 for rid in (id_a, id_b)}
    for k in keys:
        for rid, tbl in ((id_a, a), (id_b, b)):
            for f in FIELDS:
                v = (tbl[k].get(f) or "").strip()
                if v not in VALUES and v != "na":
                    unrated[rid] += 1
    w("## Completeness")
    w("")
    for rid, n in unrated.items():
        w(f"- `{rid}`: **{n}** unrated cells" + ("" if n else " — complete"))
    if any(unrated.values()):
        w("")
        w("> Unrated cells are excluded pairwise below. The protocol requires two complete "
          "passes before the results are transferred to the manuscript.")
    w("")

    # --- agreement ----------------------------------------------------------
    w("## Agreement by field")
    w("")
    w("`n` counts items where both reviewers gave one of yes/no/uncertain. "
      "Binary columns use the conservative collapse; `uncertain` fails.")
    w("")
    w("| Field | n | Raw agreement | Three-class kappa | Binary agreement | Binary kappa | PABAK |")
    w("|---|---:|---:|---:|---:|---:|---:|")

    floor_report = {}
    for f, spec in FIELDS.items():
        pairs = []
        for k in keys:
            va, vb = (a[k].get(f) or "").strip(), (b[k].get(f) or "").strip()
            if va in VALUES and vb in VALUES:
                pairs.append((va, vb))
        if not pairs:
            w(f"| `{f}` | 0 | — | — | — | — | — |")
            continue
        raw = sum(1 for x, y in pairs if x == y) / len(pairs)
        k3 = cohen_kappa(pairs)
        bp = [(x == spec["pass_on"], y == spec["pass_on"]) for x, y in pairs]
        bpairs = [("pass" if x else "fail", "pass" if y else "fail") for x, y in bp]
        braw = sum(1 for x, y in bpairs if x == y) / len(bpairs)
        k2 = cohen_kappa(bpairs)
        fmt = lambda v: "undefined" if v is None else f"{v:.3f}"
        tag = " *(descriptive)*" if spec["descriptive"] else ""
        w(f"| `{f}`{tag} | {len(pairs)} | {raw*100:.1f}% | {fmt(k3)} | "
          f"{braw*100:.1f}% | {fmt(k2)} | {pabak(braw):.3f} |")
        if f in FLOOR_FIELDS:
            floor_report[f] = (raw, k2, len(pairs))

    w("")
    w("Kappa is reported as *undefined* when one label saturates both raters; in that case "
      "raw agreement and PABAK carry the information, which is the kappa paradox the protocol "
      "requires us to disclose rather than hide.")
    w("")

    # --- quality floor ------------------------------------------------------
    w("## Predeclared rater-quality floor")
    w("")
    w(f"Floor: raw agreement ≥ {FLOOR_RAW:.0%} **and** binary kappa ≥ {FLOOR_KAPPA:.2f} on "
      f"`{'` and `'.join(FLOOR_FIELDS)}`.")
    w("")
    passed = True
    for f, (raw, k2, n) in floor_report.items():
        ok_raw = raw >= FLOOR_RAW
        ok_k = k2 is not None and k2 >= FLOOR_KAPPA
        # A saturated field with very high raw agreement cannot fail on an undefined kappa.
        if k2 is None and raw >= FLOOR_RAW:
            ok_k, note = True, " (kappa undefined; raw agreement carries the floor)"
        else:
            note = ""
        passed &= ok_raw and ok_k
        w(f"- `{f}` (n={n}): raw {raw*100:.1f}% "
          f"{'✓' if ok_raw else '✗'}, binary kappa {'undefined' if k2 is None else f'{k2:.3f}'} "
          f"{'✓' if ok_k else '✗'}{note}")
    w("")
    w(f"**Floor {'met' if passed else 'NOT met'}.**")
    if not passed:
        w("")
        w("> The protocol response is to recalibrate on 20 items and re-rate. Do not invent a "
          "third statistic, and do not add perceptual sentences to the manuscript.")
    w("")

    # --- adjudication -------------------------------------------------------
    disagree = []
    for k in keys:
        for f in FIELDS:
            va, vb = (a[k].get(f) or "").strip(), (b[k].get(f) or "").strip()
            if va in VALUES and vb in VALUES and va != vb:
                disagree.append({
                    "sample_id": k[0], "condition": k[1], "field": f,
                    f"{id_a}": va, f"{id_b}": vb, "adjudicated": "", "adjudication_note": "",
                })
    adj_path = OUT_DIR / "ADJUDICATION.csv"
    with adj_path.open("w", newline="") as fh:
        wr = csv.DictWriter(fh, fieldnames=list(disagree[0].keys()) if disagree else
                            ["sample_id", "condition", "field", id_a, id_b,
                             "adjudicated", "adjudication_note"])
        wr.writeheader()
        wr.writerows(disagree)

    w("## Adjudication")
    w("")
    w(f"**{len(disagree)}** field-level disagreements were written to "
      f"`{adj_path.relative_to(REPO)}` with an empty `adjudicated` column. The protocol requires "
      "100% of them to be resolved jointly, after both independent passes, before any pass rate "
      "is reported.")
    w("")

    # --- descriptive rates --------------------------------------------------
    w("## Descriptive rates before adjudication")
    w("")
    w("Reported for orientation only. The manuscript must use adjudicated rates. "
      "Clean images are excluded because they carry no overlay.")
    w("")

    def slice_of(row):
        cond = row["condition"]
        if cond == "clean":
            return None
        if row["review_group"] == "main_60":
            return "main simple overlays"
        for style in ("simple", "news", "camouflage"):
            if cond.endswith(style):
                return f"style {style}"
        return "other"

    slices: dict[str, list[str]] = {}
    for k in keys:
        s = slice_of(a[k])
        if s:
            slices.setdefault(s, []).append(k)

    w("| Slice | Items | `text_readable` = yes (both) | `critical_damage_obscured` = no (both) | `approve` = yes (both) |")
    w("|---|---:|---:|---:|---:|")
    for s in sorted(slices):
        ks = slices[s]
        cells = []
        for f, want in (("text_readable", "yes"), ("critical_damage_obscured", "no"), ("approve", "yes")):
            n = sum(1 for k in ks if (a[k].get(f) or "").strip() in VALUES
                    and (b[k].get(f) or "").strip() in VALUES)
            hit = sum(1 for k in ks if (a[k].get(f) or "").strip() == want
                      and (b[k].get(f) or "").strip() == want)
            lo, hi = wilson(hit, n)
            cells.append(f"{hit}/{n} ({100*hit/n:.1f}%; {lo:.1f}–{hi:.1f})" if n else "—")
        w(f"| {s} | {len(ks)} | " + " | ".join(cells) + " |")
    w("")
    w("> These are the both-reviewers-agree rates, not adjudicated rates, and they gate nothing. "
      "Fill `ADJUDICATION.csv`, then recompute before writing any sentence into the manuscript.")
    w("")

    args.out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {args.out}")
    print(f"wrote {adj_path}  ({len(disagree)} disagreements)")
    print(f"quality floor: {'MET' if passed else 'NOT MET'}")


if __name__ == "__main__":
    main()
